[output]
waveform = "output/output.wav"
message = "output/out.txt"

[input]
message = "input/message.txt"

[audio]
sample_rate = 44100
frequency = 21000
n = 1

[sync]
start = "input/init_sequence.txt"
end = "input/end_sequence.txt"