[output]
waveform = "output/output.wav"
message = "output/out.txt"

[input]
message = "input/message.txt"

[audio]
sample_rate = 44100
frequency = 200
cycles_per_symbol = 2
volume = 1.0

[sync]
start = "input/init_sequence.txt"
end = "input/end_sequence.txt"